baseURL = "https://wyattj37.github.io/tennis-belt/"

languageCode = "en-us"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false
style = "github"

[[module.imports]]
path = "github.com/willfaught/paige"

[params.paige.pages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true
disable_collections = true
disable_pages = true
disable_sections = true
enableEmoji = true
external_link_new_tab = true

[params.paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true
enableEmoji = true
external_link_new_tab = true

[params.paige.site]
disable_breadcrumbs = true
enableEmoji = true
external_link_new_tab = true

[menu]

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Lineage"
pageRef = "/lineage/"
weight = 2

[[menu.main]]
name = "Player Stats"
pageRef = "/stats/"
weight = 3

[[menu.main]]
name = "About"
pageRef = "/about/"
weight = 4